version: '3'

services:
  mimesis:
    container_name: mimesis
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: mimesis
      SLEEP_TIME: 5

networks:
  default:
    external:
      name: kafka-network
